export const S = {
  page: {
    padding: "48px 40px",
    minHeight: "calc(100vh - 56px)",
    background: "#111318",
  },
  pageTitle: {
    fontSize: "36px",
    fontWeight: 800,
    color: "#e2e8f0",
    margin: 0,
    letterSpacing: "-0.03em",
  },
  mono: {
    fontFamily: "'JetBrains Mono', monospace",
  },
  label: {
    display: "block",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "10px",
    color: "#4a5568",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    marginBottom: "8px",
  },
  input: {
    width: "100%",
    background: "#111318",
    border: "1px solid #272b35",
    borderRadius: 0,
    padding: "10px 14px",
    color: "#e2e8f0",
    fontSize: "13px",
    outline: "none",
    fontFamily: "'JetBrains Mono', monospace",
    transition: "border-color 0.2s",
  },
  btnPrimary: {
    background: "#38bdf8",
    color: "#111318",
    border: "none",
    padding: "10px 20px",
    fontSize: "12px",
    fontWeight: 700,
    fontFamily: "'Syne', sans-serif",
    letterSpacing: "0.08em",
    cursor: "pointer",
    transition: "background 0.2s",
  },
  btnSecondary: {
    background: "transparent",
    color: "#7dd3fc",
    border: "1px solid #272b35",
    padding: "10px 20px",
    fontSize: "12px",
    fontFamily: "'Syne', sans-serif",
    letterSpacing: "0.08em",
    cursor: "pointer",
    transition: "all 0.2s",
  },
};